{ pkgs, ... }: {
  # Full NixOS Desktop configuration
  
  # Standard Desktop Hardware & Boot
  # imports = [ ./hardware.nix ]; # This would be generated by nixos-generate-config
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "nixos-desktop";
  networking.networkmanager.enable = true;

  time.timeZone = "Europe/Athens"; # Adjust as needed
  i18n.defaultLocale = "en_US.UTF-8";

  # Enable Niri compositor at system level
  programs.niri.enable = true;

  # Standard user
  users.users.nixos = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" ];
    initialPassword = "nixos";
    shell = pkgs.nushell;
  };

  environment.systemPackages = with pkgs; [
    git
    helix
    vim
    wget
  ];

  system.stateVersion = "24.05"; # Or latest
}
