[[language]]
name = "python"
language-id = "python"
roots = ["pyproject.toml", "uv.lock", ".git", ".venv/"]
language-servers = ["ruff", "basedpyright", "pylsp"]
auto-format = true
# formatter = { command = "", args = ["run", "ruff check --fix - | ruff format -" ] }
file-types = ["py", "ipynb"]
comment-token = "#"
shebangs = ["python"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args=["--stdio"]

[language-server.basedpyright.config]

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "nix"
language-servers = ["nixd"]
auto-format = true

[language.formatter]
command = "nix"
args = ["fmt", "-"]

[[language]]
name = "sql"

[language.formatter]
args = ["-"]
command = "sqlfmt"

[language-server]
[language-server.nu]
args = ["--lsp"]
command = "nu"

[[language]]
name = "yaml"
[language-server.yaml-language-server.config.yaml]
validation = true

[language-server.yaml-language-server.config.yaml.format]
enable = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

[language-server.nixd]
command = "nixd"
